sudo: false
language: node_js
node_js:
  - "7"

services:
  - docker

before_install:
  - docker pull influxdb:alpine
  - docker run -d -p 8086:8086 influxdb:alpine
  - docker pull redis:alpine
  - docker run -d -p 6379:6379 redis:alpine
  - docker pull mongo
  - docker run -d -p 27017:27017 mongo

script:
  - npm test

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
